export const ADD_MESSAGE = 'ADD_MESSAGE'
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED'
export const ADD_USER = 'ADD_USER'
export const FETCH_MESSAGES = 'FETCH_MESSAGES'
export const USERS_LIST = 'USERS_LIST'
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const POPULATE_MESSAGES = 'POPULATE_MESSAGES';